version: '3'
services:
    php:
        image: liammartens/php
        ports:
            - 127.0.0.1:9000:9000
        environment:
            - PHP_PORT=9000
            - PHP_MEMORY_LIMIT=128M
            - PHP_UPLOAD_MAX_FILESIZE=30M
            - PHP_MAX_FILE_UPLOADS=10
            - PHP_POST_MAX_SIZE=45M
            - PHP_DISPLAY_ERRORS=1
        volumes:
            - ./files/php/conf:/etc/php7
            - ./files/php/log:/var/log/php7
            - ./files/www:/var/www
        tty: true
        stdin_open: true
    mysql:
        image: liammartens/mysql
        ports:
            - 127.0.0.1:3306:3306
        environment:
            - MYSQL_PORT=3306
        volumes:
            - ./files/mysql/data:/var/lib/mysql
            - ./files/mysql/conf:/etc/mysql
        tty: true
        stdin_open: true
    redis:
        image: liammartens/redis
        environment:
            - REDIS_PORT=6379
        ports:
            - 127.0.0.1:6379:6379
        volumes:
            - ./files/redis/conf:/etc/redis
            - ./files/redis/log:/var/log/redis
            - ./files/redis/data:/var/lib/redis
        tty: true
        stdin_open: true
    caddy:
        image: liammartens/caddy
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./files/caddy/.caddy:/home/www-data/caddy/.caddy
            - ./files/caddy/conf:/home/www-data/caddy/conf
            - ./files/caddy/log:/home/www-data/caddy/log
            - ./files/www:/var/www
        tty: true
        stdin_open: true
